version: '3.3'
services:
    speedtest:
        restart: unless-stopped
        container_name: openspeedtest
        ports:
            - '8095:3000'
        image: openspeedtest/latest
        volumes:
            - ./volumes/letsencrypt-data:/var/log/letsencrypt