services:
    freefilesync:
        container_name: freefilesync
        user: 0:0
        ports:
            - 8098:5800
        volumes:
            - ./volumes/appdata:/config:rw
            - ./volumes/storage:/storage:rw
            - /mnt/wd_black_ext4:/mnt/wd_black_ext4
            - /mnt/wd_black_exfat:/mnt/wd_black_exfat
            - /mnt/nas:/mnt/nas:ro
            - /root/compose:/mnt/compose:ro
        image: jlesage/freefilesync
        environment:
        - PUID=0
        - PGID=0
        env_file:
            - .env