services:
  nc:
    image: nextcloud:apache
    env_file: .env
    environment:
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - ${HTTP_PORT}:80
    restart: always
    volumes:
      - ./data:/var/www/html
      - /mnt/nas/program_files/nextcloud/data:/var/www/html/data
      - /mnt/nas:/mnt/nas:ro