# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.3
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_USER=${DB_USER}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    env_file:
      - .env
    volumes:
      - '/mnt/nas/program_files/moodle/mariadb_data:/bitnami/mariadb'
  moodle:
    image: docker.io/bitnami/moodle:4.4
    ports:
      - '8099:8080'
    env_file:
      - .env
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=${DB_PORT}
      - MOODLE_DATABASE_USER=${DB_USER}
      - MOODLE_DATABASE_NAME=${DB_NAME}
      - MOODLE_DATABASE_PASSWORD=${DB_PASSWORD}
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - '/mnt/nas/program_files/moodle/moodle_data:/bitnami/moodle'
      - '/mnt/nas/program_files/moodle/moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb