#https://github.com/schech1/uptime-buddy
services:
  uptime-buddy-api:
    image: schech1/uptime-buddy-api:latest
    ports:
      - "5005:5005"
    env_file:
      - .env
    environment:
      - UPTIME_KUMA_URL=${UPTIME_KUMA_URL} # e.g. http://192.168.1.34:3002/
      - USERNAME=${USERNAME} #Optional: remove line if auth is disabled in Uptime Kuma
      - PASSWORD=${PASSWORD} #Optional: remove line if auth is disabled in Uptime Kuma
      - TOKEN=${TOKEN} # Created by iOS-App
    restart: unless-stopped