version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./volumes/st-sync:/var/syncthing
      - /mnt/nas/program_files/syncthing/shared:/shared
    ports:
      - 8091:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    #network_mode: host
    restart: unless-stopped