services:
  postgres:
    image: postgres:latest
    container_name: postgres_main
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB_NAME}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    ports:
      - "5555:5432"
    networks:
      - pg-network
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASS}
    volumes:
      - ./volumes/pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - pg-network
    env_file:
      - .env

networks:
  pg-network:

volumes:
  pg-data:
